# Generated by Django 4.2.30 on 2026-04-16 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("update", "更新"),
                            ("delete", "删除"),
                            ("export", "导出"),
                            ("execute", "执行"),
                        ],
                        max_length=16,
                        verbose_name="动作",
                    ),
                ),
                (
                    "object_app",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="对象 app"
                    ),
                ),
                (
                    "object_model",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="对象模型"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="对象 ID"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="对象摘要"
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True, default="", max_length=512, verbose_name="请求路径"
                    ),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="User-Agent",
                    ),
                ),
                (
                    "before",
                    models.JSONField(blank=True, null=True, verbose_name="变更前快照"),
                ),
                (
                    "after",
                    models.JSONField(blank=True, null=True, verbose_name="变更后快照"),
                ),
                (
                    "extra",
                    models.JSONField(blank=True, default=dict, verbose_name="扩展字段"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "db_table": "audit_event",
                "ordering": ("-create_time",),
                "indexes": [
                    models.Index(
                        fields=["action", "-create_time"],
                        name="audit_event_action_41fa83_idx",
                    ),
                    models.Index(
                        fields=["object_app", "object_model", "object_id"],
                        name="audit_event_object__e8f49a_idx",
                    ),
                ],
            },
        ),
    ]
