"""
Django settings for AITestProduct project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import importlib.util
import os
from pathlib import Path
import socket
from urllib.parse import quote_plus


def _app_installed(name: str) -> bool:
    return importlib.util.find_spec(name) is not None


def _env_bool(name: str, default: bool = False) -> bool:
    v = os.environ.get(name)
    if v is None:
        return bool(default)
    s = str(v).strip().lower()
    if s in ("1", "true", "yes", "y", "on"):
        return True
    if s in ("0", "false", "no", "n", "off"):
        return False
    return bool(default)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# Local .env loader (dev convenience)
# - 不依赖 python-dotenv，避免额外安装
# - 仅在环境变量未设置时才从 .env 注入，保证生产环境可控
# ---------------------------------------------------------------------------


def _load_local_dotenv(path: Path) -> None:
    try:
        if not path.exists() or not path.is_file():
            return
        raw = path.read_text(encoding="utf-8")
    except Exception:
        return
    for line in raw.splitlines():
        s = line.strip()
        if not s or s.startswith("#"):
            continue
        if "=" not in s:
            continue
        k, v = s.split("=", 1)
        key = k.strip()
        if not key:
            continue
        if key in os.environ:
            continue
        val = v.strip()
        # strip optional quotes
        if (val.startswith('"') and val.endswith('"')) or (
            val.startswith("'") and val.endswith("'")
        ):
            val = val[1:-1]
        os.environ[key] = val


_load_local_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# - 开发环境可缺省（自动生成临时 key），避免首次启动被阻塞
# - 生产环境必须通过环境变量注入，并在启动时强校验
DEBUG = _env_bool("DJANGO_DEBUG", default=True)
SECRET_KEY = (os.environ.get("DJANGO_SECRET_KEY") or "").strip()
if not SECRET_KEY and DEBUG:
    # 开发环境：缺省 key 仅用于本机调试，不用于生产
    SECRET_KEY = "dev-only-unsafe-secret-key"
if not SECRET_KEY and not DEBUG:
    raise RuntimeError(
        "Missing DJANGO_SECRET_KEY while DJANGO_DEBUG=0 (production safety check)."
    )

# 逗号分隔；不设时 DEBUG 下 Django 仅允许 localhost / 127.0.0.1（局域网 IP 直连后端会 DisallowedHost）。
_allowed = os.environ.get("DJANGO_ALLOWED_HOSTS", "").strip()
ALLOWED_HOSTS = ['82.157.113.232', 'ai13.yxbzs.top', 'localhost', '127.0.0.1']


# Application definition

# daphne 为可选：未安装时仍可启动 Django；跑 WebSocket 时需 `pip install daphne` 并用 daphne 启动 ASGI
_INSTALLED_PREFIX = []
if _app_installed("daphne"):
    _INSTALLED_PREFIX.append("daphne")

INSTALLED_APPS = _INSTALLED_PREFIX + [
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "django_apscheduler",
    "user.apps.UserConfig",
    "project.apps.ProjectConfig",
    "testcase.apps.TestcaseConfig",
    "execution.apps.ExecutionConfig",
    "defect.apps.DefectConfig",
    "common.apps.CommonConfig",
    "assistant.apps.AssistantConfig",
    "server_logs.apps.ServerLogsConfig",
]
if _app_installed("django_celery_results"):
    INSTALLED_APPS.append("django_celery_results")

# 未启用 GZipMiddleware：避免对 StreamingHttpResponse 做整包压缩缓冲（SSE 需逐块写出）。
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "AITestProduct.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "AITestProduct.wsgi.application"
ASGI_APPLICATION = "AITestProduct.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("DB_NAME", "ai_test_product"),
        "USER": os.environ.get("DB_USER", "root"),
        # 开发/生产均建议通过环境变量注入，避免把密码写死到仓库中。
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
        "PORT": os.environ.get("DB_PORT", "3306"),
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",  # 严格模式，避免截断数据
        },
    }
}

if not DEBUG:
    # 生产安全：数据库密码不得为空（开发环境允许空密码/本地免密）
    if not str(DATABASES["default"].get("PASSWORD") or "").strip():
        raise RuntimeError(
            "Missing DB_PASSWORD while DJANGO_DEBUG=0 (production safety check)."
        )


REST_FRAMEWORK = {
    # 默认认证方式：Token认证
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
    ),
    # 默认权限策略：必须是登录用户（IsAuthenticated）
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    # ScopedRateThrottle 的配额（仅对声明了 throttle_scope 的视图生效）
    "DEFAULT_THROTTLE_RATES": {
        "server_logs_analyze": os.environ.get(
            "SERVER_LOGS_ANALYZE_THROTTLE", "40/hour"
        ),
    },
}

# ----------------------------
# Cache（验证码依赖）
# ----------------------------
# 你的运行环境里可能没有 Redis 或 Redis 未启动。
# 为了避免验证码接口因缓存后端连接失败直接 500，这里做 Redis 不可用时的自动降级。
_redis_host = os.environ.get("REDIS_HOST", "127.0.0.1")
_redis_port = int(os.environ.get("REDIS_PORT", "6379"))
_use_redis_cache = os.environ.get("USE_REDIS_CACHE", "1") == "1"


def _redis_is_available(host: str, port: int, timeout: float = 0.3) -> bool:
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


_channel_redis_host = os.environ.get("CHANNEL_REDIS_HOST", _redis_host)
_channel_redis_port = int(os.environ.get("CHANNEL_REDIS_PORT", str(_redis_port)))

# Channels：与缓存一致，Redis 不可用时降级内存层（单机开发可用；多进程/生产请启动 Redis）。
if _redis_is_available(_channel_redis_host, _channel_redis_port):
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [(_channel_redis_host, _channel_redis_port)],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/0", # 这里的 host 写死 127.0.0.1
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},
        },
    }
}

# 可选配置：将会话（Session）引擎也改为使用 Redis，提升 Session 存取速度
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATIC_URL = "static/"

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# ----------------------------
# Media (上传图片/文件)
# ----------------------------
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# 指定系统的主力用户模型为 user 应用下的 User 模型
AUTH_USER_MODEL = "user.User"

# ---------------------------------------------------------------------------
# 登录密码兼容（默认全部关闭；与 Django 默认行为一致：前端传明文，库中为 Django 哈希）
#
# 若历史数据把「MD5(明文)」存在 password 字段，设为 1 后可用明文登录，成功后自动改为标准哈希。
# 若前端提交的是 MD5 十六进制且库里也是同一段 MD5，用 LEGACY_LOGIN_BOTH_SIDES_MD5_HEX。
# ---------------------------------------------------------------------------
LEGACY_LOGIN_MD5_HEX = os.environ.get("LEGACY_LOGIN_MD5_HEX", "0") == "1"
LEGACY_LOGIN_SHA256_HEX = os.environ.get("LEGACY_LOGIN_SHA256_HEX", "0") == "1"
LEGACY_LOGIN_BOTH_SIDES_MD5_HEX = (
    os.environ.get("LEGACY_LOGIN_BOTH_SIDES_MD5_HEX", "0") == "1"
)
LEGACY_LOGIN_PLAINTEXT = os.environ.get("LEGACY_LOGIN_PLAINTEXT", "0") == "1"

# ---------------------------------------------------------------------------
# 邮件发送（用户中心：敏感变更通知管理员）
# ---------------------------------------------------------------------------
# 1) 开发调试：邮件只打印到控制台，无需 SMTP
#    EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
# 2) 生产（示例）：填写 SMTP 与发件人，并设置管理员收件人
#
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.example.com"
# EMAIL_PORT = 587
# EMAIL_HOST_USER = "your-smtp-user"
# EMAIL_HOST_PASSWORD = "your-smtp-password"
# EMAIL_USE_TLS = True
# DEFAULT_FROM_EMAIL = "AITest <noreply@example.com>"
# SERVER_EMAIL = DEFAULT_FROM_EMAIL
#
# 审核邮件收件人（逗号分隔多个邮箱）；若不设置则回退到 ADMINS
USER_CENTER_ADMIN_EMAIL = os.environ.get("USER_CENTER_ADMIN_EMAIL", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "webmaster@localhost")
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
EMAIL_SUBJECT_PREFIX = os.environ.get("EMAIL_SUBJECT_PREFIX", "[AITest]")
# 若未设置 USER_CENTER_ADMIN_EMAIL，将使用 ADMINS 中的邮箱（Django 默认空）
ADMINS = []

# 环境变量加密密钥（Fernet key）。生产建议通过环境变量注入独立密钥。
AITEST_ENV_SECRET_KEY = os.environ.get("AITEST_ENV_SECRET_KEY", "")

# ---------------------------------------------------------------------------
# Celery（执行引擎异步任务）
# ---------------------------------------------------------------------------
_db_default = DATABASES.get("default", {})
_db_user = quote_plus(str(_db_default.get("USER", "") or ""))
_db_password = quote_plus(str(_db_default.get("PASSWORD", "") or ""))
_db_host = str(_db_default.get("HOST", "") or "127.0.0.1")
_db_port = str(_db_default.get("PORT", "") or "3306")
_db_name = str(_db_default.get("NAME", "") or "")
_auth_part = _db_user
if _db_password:
    _auth_part = f"{_db_user}:{_db_password}"
# 使用 SQLAlchemy 传输层，将 Celery Broker 切换到 MySQL。
# 连接信息复用 Django DATABASES['default']，避免重复维护配置。
_default_mysql_broker = (
    f"sqla+mysql+pymysql://{_auth_part}@{_db_host}:{_db_port}/{_db_name}"
)
# 优先使用 Redis（更常见、更轻量的 broker）；Redis 不可用则回退 MySQL broker。
_default_redis_broker = f"redis://{_redis_host}:{_redis_port}/1"
if _redis_is_available(_redis_host, _redis_port):
    _default_broker = _default_redis_broker
else:
    _default_broker = _default_mysql_broker
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", _default_broker)
# 若安装了 django-celery-results，则可用 django-db 作为结果后端；否则回退到 rpc://，避免配置为不可用的 backend。
CELERY_RESULT_BACKEND = os.environ.get(
    "CELERY_RESULT_BACKEND",
    "django-db" if _app_installed("django_celery_results") else "rpc://",
)
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# 知识库上传解析：单文件大小限制（字节）
KNOWLEDGE_UPLOAD_MAX_SIZE = int(
    os.environ.get("KNOWLEDGE_UPLOAD_MAX_SIZE", str(10 * 1024 * 1024))
)

# RAG 参数：检索召回条数与上下文截断长度
RAG_TOP_K = int(os.environ.get("RAG_TOP_K", "5"))
RAG_MAX_CONTEXT_CHARS = int(os.environ.get("RAG_MAX_CONTEXT_CHARS", "1200"))
# 知识中心 Embedding 提供方（openai/ollama）。
# 默认 openai；若未配置 OPENAI_API_KEY，任务层会自动尝试降级到 ollama。
KNOWLEDGE_EMBEDDING_PROVIDER = os.environ.get("KNOWLEDGE_EMBEDDING_PROVIDER", "openai")

# AI 生成测试用例：最小条数兜底（不足时触发二次补生成）
AI_GENERATE_MIN_CASES = int(os.environ.get("AI_GENERATE_MIN_CASES", "4"))
# AI 生成测试用例：最多保留条数（防止返回过大）
AI_GENERATE_MAX_CASES = int(os.environ.get("AI_GENERATE_MAX_CASES", "20"))
# AI 生成测试用例：最小条数补生成的最大轮次
AI_GENERATE_RETRY_ROUNDS = int(os.environ.get("AI_GENERATE_RETRY_ROUNDS", "2"))
# AI 批量生成：单次最少条数（用于 Batch Prompt 约束）
AI_CASE_BATCH_MIN_COUNT = int(os.environ.get("AI_CASE_BATCH_MIN_COUNT", "5"))
# AI 语义去重：相似度阈值（>= 阈值判定为重复并剔除）
AI_CASE_SEMANTIC_DUP_THRESHOLD = float(
    os.environ.get("AI_CASE_SEMANTIC_DUP_THRESHOLD", "0.85")
)

# ---------------------------------------------------------------------------
# AI 治理：配额/并发保护（最小可用版，按用户维度）
# ---------------------------------------------------------------------------
# 0 表示不启用每日配额（默认不限制，建议生产环境配置）
AI_GUARD_DAILY_REQUESTS = int(os.environ.get("AI_GUARD_DAILY_REQUESTS", "0"))
# 单用户最大并发（同步+流式算在一起）；0 表示不限制（不建议）
AI_GUARD_MAX_CONCURRENCY = int(os.environ.get("AI_GUARD_MAX_CONCURRENCY", "2"))
# 并发槽位 TTL：用于异常中断时自动释放（秒）
AI_GUARD_CONCURRENCY_TTL_SECONDS = int(
    os.environ.get("AI_GUARD_CONCURRENCY_TTL_SECONDS", "180")
)

# ---------------------------------------------------------------------------
# 服务器日志模块（SSH / Loki）
# ---------------------------------------------------------------------------
# 独立 Fernet 密钥（url-safe base64 44 字符）；不设置则从 SECRET_KEY 派生（仅建议开发环境）。
SERVER_LOGS_FERNET_KEY = os.environ.get("SERVER_LOGS_FERNET_KEY", "")
# Grafana Loki 根地址（如 https://loki.example.com），留空则历史检索接口返回未启用。
SERVER_LOGS_LOKI_BASE = os.environ.get("SERVER_LOGS_LOKI_BASE", "")
# Elasticsearch：server_logs 实时写入与历史检索。生产务必用环境变量覆盖 URL 与密码。
ELASTICSEARCH_URL = os.environ.get("ELASTICSEARCH_URL", "http://localhost:9200")
ELASTICSEARCH_USER = os.environ.get("ELASTICSEARCH_USER", "elastic")
ELASTICSEARCH_PASSWORD = os.environ.get("ELASTICSEARCH_PASSWORD", "")
_es_verify = os.environ.get("ELASTICSEARCH_VERIFY_CERTS", "").strip().lower()
ELASTICSEARCH_VERIFY_CERTS = _es_verify in ("1", "true", "yes")
ELASTICSEARCH_REQUEST_TIMEOUT = int(
    os.environ.get("ELASTICSEARCH_REQUEST_TIMEOUT", "5")
)
# 读写别名（与 ILM rollover 一致）；若自建集群改了别名，需同步改此项与模板中的物理索引前缀。
SERVER_LOGS_ES_INDEX = os.environ.get("SERVER_LOGS_ES_INDEX", "server-logs")

# 远程 SSH 日志 tail：主机密钥策略（对齐安全审计 Bandit B507 / MITM 风险）。
# - auto_add：等同 Paramiko AutoAddPolicy（仅建议开发 / 明确接受风险的环境）
# - warning：Paramiko WarningPolicy（未知指纹仍连接，控制台告警）
# - reject：加载系统 known_hosts（~/.ssh/known_hosts 等）+ RejectPolicy（生产默认，当 DEBUG=0）
# - known_hosts：仅信任 SERVER_LOGS_SSH_KNOWN_HOSTS_PATH 文件中的指纹 + RejectPolicy
_server_logs_ssh_policy = os.environ.get(
    "SERVER_LOGS_SSH_HOST_KEY_POLICY", ""
).strip().lower()
if _server_logs_ssh_policy:
    SERVER_LOGS_SSH_HOST_KEY_POLICY = _server_logs_ssh_policy
else:
    SERVER_LOGS_SSH_HOST_KEY_POLICY = "auto_add" if DEBUG else "reject"
SERVER_LOGS_SSH_KNOWN_HOSTS_PATH = os.environ.get(
    "SERVER_LOGS_SSH_KNOWN_HOSTS_PATH", ""
).strip()

if not DEBUG:
    # 生产安全：若配置了 ES 用户则要求密码不为空（允许匿名集群：用户为空时不做强校验）
    if (
        str(ELASTICSEARCH_USER or "").strip()
        and not str(ELASTICSEARCH_PASSWORD or "").strip()
    ):
        raise RuntimeError(
            "Missing ELASTICSEARCH_PASSWORD while DJANGO_DEBUG=0 (production safety check)."
        )

# 允许上传的最大请求体大小（单位：字节，这里设置为 20MB）
DATA_UPLOAD_MAX_MEMORY_SIZE = 20971520

# 允许上传的最大文件大小（单位：字节，这里设置为 20MB）
FILE_UPLOAD_MAX_MEMORY_SIZE = 20971520
