"""
Django settings for AITestProduct project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import importlib.util
import os
from pathlib import Path
import socket
from urllib.parse import quote_plus


def _app_installed(name: str) -> bool:
    return importlib.util.find_spec(name) is not None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-oc-#_d1n+y92e3n3y-agvr4l4t20ehs=i+d6vpwho^9_k%-lgv"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# daphne 为可选：未安装时仍可启动 Django；跑 WebSocket 时需 `pip install daphne` 并用 daphne 启动 ASGI
_INSTALLED_PREFIX = []
if _app_installed("daphne"):
    _INSTALLED_PREFIX.append("daphne")

INSTALLED_APPS = _INSTALLED_PREFIX + [
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework.authtoken',
    "django_apscheduler",
    "user.apps.UserConfig",
    "project.apps.ProjectConfig",
    "testcase.apps.TestcaseConfig",
    "execution.apps.ExecutionConfig",
    "defect.apps.DefectConfig",
    "common.apps.CommonConfig",
    "assistant.apps.AssistantConfig",
]
if _app_installed("django_celery_results"):
    INSTALLED_APPS.append("django_celery_results")

# 未启用 GZipMiddleware：避免对 StreamingHttpResponse 做整包压缩缓冲（SSE 需逐块写出）。
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "AITestProduct.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "AITestProduct.wsgi.application"
ASGI_APPLICATION = "AITestProduct.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "ai_test_product",  # 刚刚第一步创建的数据库名称
        "USER": "root",  # 您的 MySQL 用户名
        "PASSWORD": "Jj123456.",  # 您的 MySQL 密码（请替换为实际密码）
        "HOST": "127.0.0.1",  # 本地数据库地址
        "PORT": "3306",  # MySQL 默认端口
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",  # 严格模式，避免截断数据
        },
    }
}


REST_FRAMEWORK = {
    # 默认认证方式：Token认证
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    # 默认权限策略：必须是登录用户（IsAuthenticated）
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# ----------------------------
# Cache（验证码依赖）
# ----------------------------
# 你的运行环境里可能没有 Redis 或 Redis 未启动。
# 为了避免验证码接口因缓存后端连接失败直接 500，这里做 Redis 不可用时的自动降级。
_redis_host = os.environ.get("REDIS_HOST", "127.0.0.1")
_redis_port = int(os.environ.get("REDIS_PORT", "6379"))
_use_redis_cache = os.environ.get("USE_REDIS_CACHE", "1") == "1"

# Django Channels（须在 _redis_host / _redis_port 定义之后，避免 NameError）
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                (
                    os.environ.get("CHANNEL_REDIS_HOST", _redis_host),
                    int(os.environ.get("CHANNEL_REDIS_PORT", str(_redis_port))),
                )
            ],
        },
    },
}


def _redis_is_available(host: str, port: int, timeout: float = 0.3) -> bool:
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


if _use_redis_cache and _redis_is_available(_redis_host, _redis_port):
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": f"redis://{_redis_host}:{_redis_port}/0",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "CONNECTION_POOL_KWARGS": {"max_connections": 100},
            },
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-per-process",
            "TIMEOUT": 300,
        }
    }

# 可选配置：将会话（Session）引擎也改为使用 Redis，提升 Session 存取速度
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# ----------------------------
# Media (上传图片/文件)
# ----------------------------
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# 指定系统的主力用户模型为 user 应用下的 User 模型
AUTH_USER_MODEL = "user.User"

# ---------------------------------------------------------------------------
# 登录密码兼容（默认全部关闭；与 Django 默认行为一致：前端传明文，库中为 Django 哈希）
#
# 若历史数据把「MD5(明文)」存在 password 字段，设为 1 后可用明文登录，成功后自动改为标准哈希。
# 若前端提交的是 MD5 十六进制且库里也是同一段 MD5，用 LEGACY_LOGIN_BOTH_SIDES_MD5_HEX。
# ---------------------------------------------------------------------------
LEGACY_LOGIN_MD5_HEX = os.environ.get("LEGACY_LOGIN_MD5_HEX", "0") == "1"
LEGACY_LOGIN_SHA256_HEX = os.environ.get("LEGACY_LOGIN_SHA256_HEX", "0") == "1"
LEGACY_LOGIN_BOTH_SIDES_MD5_HEX = (
    os.environ.get("LEGACY_LOGIN_BOTH_SIDES_MD5_HEX", "0") == "1"
)
LEGACY_LOGIN_PLAINTEXT = os.environ.get("LEGACY_LOGIN_PLAINTEXT", "0") == "1"

# ---------------------------------------------------------------------------
# 邮件发送（用户中心：敏感变更通知管理员）
# ---------------------------------------------------------------------------
# 1) 开发调试：邮件只打印到控制台，无需 SMTP
#    EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
# 2) 生产（示例）：填写 SMTP 与发件人，并设置管理员收件人
#
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.example.com"
# EMAIL_PORT = 587
# EMAIL_HOST_USER = "your-smtp-user"
# EMAIL_HOST_PASSWORD = "your-smtp-password"
# EMAIL_USE_TLS = True
# DEFAULT_FROM_EMAIL = "AITest <noreply@example.com>"
# SERVER_EMAIL = DEFAULT_FROM_EMAIL
#
# 审核邮件收件人（逗号分隔多个邮箱）；若不设置则回退到 ADMINS
USER_CENTER_ADMIN_EMAIL = os.environ.get("USER_CENTER_ADMIN_EMAIL", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "webmaster@localhost")
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
EMAIL_SUBJECT_PREFIX = os.environ.get("EMAIL_SUBJECT_PREFIX", "[AITest]")
# 若未设置 USER_CENTER_ADMIN_EMAIL，将使用 ADMINS 中的邮箱（Django 默认空）
ADMINS = []

# 环境变量加密密钥（Fernet key）。生产建议通过环境变量注入独立密钥。
AITEST_ENV_SECRET_KEY = os.environ.get("AITEST_ENV_SECRET_KEY", "")

# ---------------------------------------------------------------------------
# Celery（执行引擎异步任务）
# ---------------------------------------------------------------------------
_db_default = DATABASES.get("default", {})
_db_user = quote_plus(str(_db_default.get("USER", "") or ""))
_db_password = quote_plus(str(_db_default.get("PASSWORD", "") or ""))
_db_host = str(_db_default.get("HOST", "") or "127.0.0.1")
_db_port = str(_db_default.get("PORT", "") or "3306")
_db_name = str(_db_default.get("NAME", "") or "")
_auth_part = _db_user
if _db_password:
    _auth_part = f"{_db_user}:{_db_password}"
# 使用 SQLAlchemy 传输层，将 Celery Broker 切换到 MySQL。
# 连接信息复用 Django DATABASES['default']，避免重复维护配置。
_default_mysql_broker = (
    f"sqla+mysql+pymysql://{_auth_part}@{_db_host}:{_db_port}/{_db_name}"
)
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", _default_mysql_broker)
# 若安装了 django-celery-results，则统一使用 django-db 作为结果后端。
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "django-db")
CELERY_TASK_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# 知识库上传解析：单文件大小限制（字节）
KNOWLEDGE_UPLOAD_MAX_SIZE = int(
    os.environ.get("KNOWLEDGE_UPLOAD_MAX_SIZE", str(10 * 1024 * 1024))
)

# RAG 参数：检索召回条数与上下文截断长度
RAG_TOP_K = int(os.environ.get("RAG_TOP_K", "5"))
RAG_MAX_CONTEXT_CHARS = int(os.environ.get("RAG_MAX_CONTEXT_CHARS", "1200"))
# 知识中心 Embedding 提供方（openai/ollama）。
# 默认 openai；若未配置 OPENAI_API_KEY，任务层会自动尝试降级到 ollama。
KNOWLEDGE_EMBEDDING_PROVIDER = os.environ.get("KNOWLEDGE_EMBEDDING_PROVIDER", "openai")

# AI 生成测试用例：最小条数兜底（不足时触发二次补生成）
AI_GENERATE_MIN_CASES = int(os.environ.get("AI_GENERATE_MIN_CASES", "4"))
# AI 生成测试用例：最多保留条数（防止返回过大）
AI_GENERATE_MAX_CASES = int(os.environ.get("AI_GENERATE_MAX_CASES", "20"))
# AI 生成测试用例：最小条数补生成的最大轮次
AI_GENERATE_RETRY_ROUNDS = int(os.environ.get("AI_GENERATE_RETRY_ROUNDS", "2"))
# AI 批量生成：单次最少条数（用于 Batch Prompt 约束）
AI_CASE_BATCH_MIN_COUNT = int(os.environ.get("AI_CASE_BATCH_MIN_COUNT", "5"))
# AI 语义去重：相似度阈值（>= 阈值判定为重复并剔除）
AI_CASE_SEMANTIC_DUP_THRESHOLD = float(
    os.environ.get("AI_CASE_SEMANTIC_DUP_THRESHOLD", "0.85")
)


