# Generated by Django 4.2.20 on 2026-04-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestApproach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="逻辑删除标识"),
                ),
                (
                    "scheme_name",
                    models.CharField(max_length=255, verbose_name="方案名称"),
                ),
                ("version", models.CharField(max_length=255, verbose_name="版本")),
                (
                    "cover_image",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="封面图"
                    ),
                ),
            ],
            options={
                "db_table": "test_approach",
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="逻辑删除标识"),
                ),
                (
                    "case_name",
                    models.CharField(max_length=255, verbose_name="用例名称"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("P0", "P0"),
                            ("P1", "P1"),
                            ("P2", "P2"),
                            ("P3", "P3"),
                        ],
                        default="P2",
                        max_length=10,
                        verbose_name="用例等级",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                ("exec_count", models.IntegerField(default=0, verbose_name="执行次数")),
                (
                    "review_status",
                    models.IntegerField(
                        choices=[(1, "未评审"), (2, "评审中"), (3, "已评审")],
                        default=1,
                        verbose_name="评审状态",
                    ),
                ),
                (
                    "archive_status",
                    models.IntegerField(
                        choices=[(1, "未归档"), (2, "已归档")],
                        default=1,
                        verbose_name="归档状态",
                    ),
                ),
            ],
            options={
                "db_table": "test_case",
            },
        ),
        migrations.CreateModel(
            name="TestCaseStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="逻辑删除标识"),
                ),
                ("step_number", models.IntegerField(verbose_name="步骤编号")),
                ("step_desc", models.TextField(verbose_name="步骤描述")),
                ("expected_result", models.TextField(verbose_name="预期结果")),
            ],
            options={
                "db_table": "test_case_step",
                "ordering": ["step_number"],
            },
        ),
        migrations.CreateModel(
            name="TestDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="逻辑删除标识"),
                ),
                (
                    "design_name",
                    models.CharField(max_length=255, verbose_name="设计名称"),
                ),
                ("req_count", models.IntegerField(default=0, verbose_name="需求数量")),
                (
                    "point_count",
                    models.IntegerField(default=0, verbose_name="测试点数量"),
                ),
                ("case_count", models.IntegerField(default=0, verbose_name="用例数量")),
                (
                    "review_status",
                    models.IntegerField(
                        choices=[(1, "未评审"), (2, "评审中"), (3, "已评审")],
                        default=1,
                        verbose_name="评审状态",
                    ),
                ),
                (
                    "archive_status",
                    models.IntegerField(
                        choices=[(1, "未归档"), (2, "已归档")],
                        default=1,
                        verbose_name="归档状态",
                    ),
                ),
            ],
            options={
                "db_table": "test_design",
            },
        ),
        migrations.CreateModel(
            name="TestModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="逻辑删除标识"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模块名称")),
            ],
            options={
                "db_table": "test_module",
            },
        ),
    ]
