# Generated by Django 4.2.20 on 2026-04-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcase", "0004_testapproachimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="test_type",
            field=models.CharField(
                choices=[
                    ("functional", "功能测试"),
                    ("api", "API 测试"),
                    ("performance", "性能测试"),
                    ("security", "安全测试"),
                ],
                default="functional",
                max_length=32,
                verbose_name="测试类型",
            ),
        ),
    ]
