# Generated by Django 4.2.20 on 2026-04-09 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testcase", "0013_execution_log_and_api_body_json"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="executionlog",
            new_name="api_executi_test_ca_0661b3_idx",
            old_name="api_exec_case_ctime_idx",
        ),
        migrations.AlterField(
            model_name="executionlog",
            name="assertion_results",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='示例: [{"name":"status","passed":true,"detail":"..."}]',
                verbose_name="断言结果",
            ),
        ),
        migrations.AlterField(
            model_name="executionlog",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="executionlog",
            name="updater",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
    ]
