# Generated by Django 4.2.20 on 2026-04-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcase", "0015_executionlog_trace_request_response_payload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitestlog",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除"),
        ),
        migrations.AlterField(
            model_name="executionlog",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除"),
        ),
        migrations.AlterField(
            model_name="testapproach",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除"),
        ),
        migrations.AlterField(
            model_name="testapproachimage",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除"),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除"),
        ),
        migrations.AlterField(
            model_name="testcasestep",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除"),
        ),
        migrations.AlterField(
            model_name="testdesign",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除"),
        ),
        migrations.AlterField(
            model_name="testmodule",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除"),
        ),
    ]
