# Generated by Django 4.2.20 on 2026-04-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcase", "0016_alter_apitestlog_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="securitytestcase",
            name="risk_level",
            field=models.CharField(
                blank=True,
                choices=[("高", "高"), ("中", "中"), ("低", "低")],
                default="",
                max_length=8,
                verbose_name="风险等级",
            ),
        ),
    ]
