# Generated by Django 4.2.30 on 2026-04-09 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testcase", "0017_securitytestcase_risk_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestEnvironment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="环境名称"
                    ),
                ),
                (
                    "env_type",
                    models.CharField(
                        choices=[
                            ("dev", "开发环境"),
                            ("test", "测试环境"),
                            ("staging", "预发环境"),
                            ("prod", "生产镜像"),
                            ("custom", "自定义"),
                        ],
                        default="test",
                        max_length=16,
                        verbose_name="环境类型",
                    ),
                ),
                (
                    "base_url",
                    models.CharField(
                        blank=True, default="", max_length=2048, verbose_name="基础地址"
                    ),
                ),
                (
                    "db_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="示例：{host, port, user, password, db_name}",
                        verbose_name="数据库配置(JSON)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="环境描述"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "db_table": "test_environment",
                "ordering": ("-create_time",),
            },
        ),
        migrations.CreateModel(
            name="EnvironmentVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                ("key", models.CharField(max_length=128, verbose_name="变量名")),
                (
                    "value",
                    models.TextField(blank=True, default="", verbose_name="变量值"),
                ),
                (
                    "is_secret",
                    models.BooleanField(default=False, verbose_name="是否敏感变量"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="变量说明"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="testcase.testenvironment",
                        verbose_name="所属环境",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "db_table": "environment_variable",
                "ordering": ("id",),
            },
        ),
        migrations.AddConstraint(
            model_name="environmentvariable",
            constraint=models.UniqueConstraint(
                fields=("environment", "key"), name="uniq_env_var_key"
            ),
        ),
    ]
