# Generated by Django 4.2.30 on 2026-04-09 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0006_releaseplan_test_cases"),
        ("testcase", "0018_testenvironment_environmentvariable_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCaseVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                ("version_label", models.CharField(max_length=64, verbose_name="版本标签")),
                ("case_snapshot", models.JSONField(blank=True, default=dict, verbose_name="用例快照")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "release_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_versions",
                        to="project.releaseplan",
                        verbose_name="发布计划",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="testcase.testcase",
                        verbose_name="测试用例",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "db_table": "test_case_version",
                "ordering": ("-create_time",),
            },
        ),
        migrations.AddConstraint(
            model_name="testcaseversion",
            constraint=models.UniqueConstraint(
                fields=("test_case", "release_plan"),
                name="uniq_case_version_per_release",
            ),
        ),
    ]
