# Generated by Django 4.2.30 on 2026-04-09 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testcase", "0019_testcaseversion"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="testcaseversion",
            name="uniq_case_version_per_release",
        ),
        migrations.AddField(
            model_name="testcaseversion",
            name="snapshot_no",
            field=models.PositiveIntegerField(default=1, verbose_name="快照序号"),
        ),
        migrations.AddField(
            model_name="testcaseversion",
            name="source_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_versions",
                to="testcase.testcaseversion",
                verbose_name="来源快照",
            ),
        ),
        migrations.AddIndex(
            model_name="testcaseversion",
            index=models.Index(
                fields=["test_case", "release_plan", "-snapshot_no"],
                name="test_case_ve_test_ca_987f15_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="testcaseversion",
            index=models.Index(
                fields=["release_plan", "-create_time"],
                name="test_case_ve_release_f521f1_idx",
            ),
        ),
    ]
