# Generated by Django 4.2.30 on 2026-04-09 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testcase", "0020_testcaseversion_multiversion"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvironmentHealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[("db", "DB"), ("api", "API"), ("redis", "Redis")],
                        max_length=16,
                        verbose_name="检查类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("healthy", "Healthy"), ("unhealthy", "Unhealthy")],
                        max_length=16,
                        verbose_name="健康状态",
                    ),
                ),
                ("response_time_ms", models.PositiveIntegerField(default=0, verbose_name="响应时间(ms)")),
                ("error_log", models.TextField(blank=True, default="", verbose_name="错误日志")),
                ("target", models.CharField(blank=True, default="", max_length=255, verbose_name="检查目标")),
                ("dimension", models.JSONField(blank=True, default=dict, verbose_name="维度信息")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "db_table": "environment_health_check",
                "ordering": ("-create_time",),
            },
        ),
        migrations.AddIndex(
            model_name="environmenthealthcheck",
            index=models.Index(
                fields=["check_type", "status", "-create_time"],
                name="environmen_check_t_fed64f_idx",
            ),
        ),
    ]
