# Generated by Django 4.2.30 on 2026-04-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("testcase", "0021_environmenthealthcheck"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="environmenthealthcheck",
            new_name="environment_check_t_7d05e0_idx",
            old_name="environmen_check_t_fed64f_idx",
        ),
        migrations.RenameIndex(
            model_name="testcaseversion",
            new_name="test_case_v_test_ca_f55dbc_idx",
            old_name="test_case_ve_test_ca_987f15_idx",
        ),
        migrations.RenameIndex(
            model_name="testcaseversion",
            new_name="test_case_v_release_a50b5e_idx",
            old_name="test_case_ve_release_f521f1_idx",
        ),
    ]
