# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "testcase",
            "0022_rename_environmen_check_t_fed64f_idx_environment_check_t_7d05e0_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="testenvironment",
            name="health_check_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="相对路径，如 health、api/health；留空则对 Base URL 根路径发 GET",
                max_length=512,
                verbose_name="健康检查路径",
            ),
        ),
    ]
