# Generated by Django 4.2.20 on 2026-04-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcase", "0023_testenvironment_health_check_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitestcase",
            name="api_source_curl",
            field=models.TextField(
                blank=True,
                default="",
                help_text="生成或「从 cURL 填充」时保存的原始命令；执行前可据此还原请求",
                verbose_name="来源 cURL",
            ),
        ),
    ]
