# Generated by Django 4.2.30 on 2026-04-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcase", "0026_testcase_ai_run_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcasestep",
            name="assertions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='示例: [{"type":"jsonpath_equals","path":"$.code","expected":200}]；为空则仅执行基础断言（状态码 + 预期结果子串）',
                verbose_name="断言配置(JSON)",
            ),
        ),
    ]
