# Generated by Django 4.2.30 on 2026-04-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcase", "0027_testcasestep_assertions"),
    ]

    operations = [
        migrations.AddField(
            model_name="testenvironment",
            name="auth_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='示例: {"type":"bearer","token_var":"token","header":"Authorization","prefix":"Bearer "} 或 {"type":"api_key","header":"X-API-Key","value_var":"api_key"}',
                verbose_name="鉴权配置(JSON)",
            ),
        ),
    ]
