# Generated by Django 4.2.20 on 2026-04-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestDefect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="逻辑删除标识"),
                ),
                (
                    "defect_no",
                    models.CharField(max_length=255, verbose_name="缺陷编号"),
                ),
                (
                    "defect_name",
                    models.CharField(max_length=255, verbose_name="缺陷标题"),
                ),
                (
                    "severity",
                    models.IntegerField(
                        choices=[(1, "致命"), (2, "严重"), (3, "一般"), (4, "建议")],
                        default=3,
                        verbose_name="严重程度",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[(1, "高"), (2, "中"), (3, "低")],
                        default=2,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "新缺陷"),
                            (2, "处理中"),
                            (3, "已拒绝"),
                            (4, "已关闭"),
                        ],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "db_table": "test_defect",
            },
        ),
    ]
