# Generated by Django 4.2.20 on 2026-04-01 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0001_initial"),
        ("defect", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testdefect",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="testdefect",
            name="handler",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="handled_defects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="当前处理人",
            ),
        ),
        migrations.AddField(
            model_name="testdefect",
            name="release_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="defects",
                to="project.releaseplan",
                verbose_name="关联版本",
            ),
        ),
        migrations.AddField(
            model_name="testdefect",
            name="updater",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
    ]
