# Generated by Django 4.2.20 on 2026-04-02 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testcase", "0002_initial"),
        ("defect", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testdefect",
            name="defect_content",
            field=models.TextField(blank=True, null=True, verbose_name="缺陷内容"),
        ),
        migrations.AddField(
            model_name="testdefect",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="defects",
                to="testcase.testmodule",
                verbose_name="所属模块",
            ),
        ),
    ]
