# Generated by Django 4.2.20 on 2026-04-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defect", "0003_testdefect_defect_content_testdefect_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testdefect",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除"),
        ),
    ]
