# Generated by Django 4.2.30 on 2026-04-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defect", "0004_alter_testdefect_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="testdefect",
            name="attachments",
            field=models.JSONField(blank=True, default=list, verbose_name="附件列表"),
        ),
        migrations.AddField(
            model_name="testdefect",
            name="environment",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="发生环境"
            ),
        ),
        migrations.AddField(
            model_name="testdefect",
            name="reproduction_steps",
            field=models.JSONField(blank=True, default=list, verbose_name="复现步骤"),
        ),
        migrations.AddConstraint(
            model_name="testdefect",
            constraint=models.UniqueConstraint(
                fields=("defect_no", "is_deleted"),
                name="uniq_test_defect_no_is_deleted",
            ),
        ),
    ]
