# Generated by Django 4.2.20 on 2026-04-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReleasePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="逻辑删除标识"),
                ),
                (
                    "release_name",
                    models.CharField(max_length=255, verbose_name="发布名称"),
                ),
                ("version_no", models.CharField(max_length=255, verbose_name="版本号")),
                ("release_date", models.DateTimeField(verbose_name="计划发布日期")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "待发布"), (2, "已发布"), (3, "已取消")],
                        default=1,
                        verbose_name="发布状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "发布计划",
                "db_table": "release_plan",
            },
        ),
        migrations.CreateModel(
            name="TestProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="逻辑删除标识"),
                ),
                (
                    "project_name",
                    models.CharField(max_length=255, verbose_name="项目名称"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="项目描述"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="项目图标"
                    ),
                ),
            ],
            options={
                "verbose_name": "项目管理",
                "db_table": "test_project",
            },
        ),
        migrations.CreateModel(
            name="TestTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="逻辑删除标识"),
                ),
                (
                    "task_title",
                    models.CharField(max_length=255, verbose_name="任务标题"),
                ),
                (
                    "task_desc",
                    models.TextField(blank=True, null=True, verbose_name="任务描述"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "待处理"), (2, "处理中"), (3, "已处理")],
                        default=1,
                        verbose_name="任务状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务看板",
                "db_table": "test_task",
            },
        ),
    ]
