# Generated by Django 4.2.20 on 2026-04-03 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testproject",
            name="progress",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="进行中时展示为 0-100；已完成可忽略",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="进度百分比",
            ),
        ),
        migrations.AddField(
            model_name="testproject",
            name="project_status",
            field=models.IntegerField(
                choices=[(1, "进行中"), (2, "已完成")],
                default=1,
                verbose_name="项目状态",
            ),
        ),
    ]
