# Generated by Django 4.2.20 on 2026-04-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_releaseplan_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="releaseplan",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除"),
        ),
        migrations.AlterField(
            model_name="testproject",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="project_covers/",
                verbose_name="项目封面图",
            ),
        ),
        migrations.AlterField(
            model_name="testproject",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除"),
        ),
        migrations.AlterField(
            model_name="testtask",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除"),
        ),
    ]
