# Generated by Django 4.2.30 on 2026-04-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcase", "0018_testenvironment_environmentvariable_and_more"),
        (
            "project",
            "0005_alter_releaseplan_is_deleted_alter_testproject_icon_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="releaseplan",
            name="test_cases",
            field=models.ManyToManyField(
                blank=True,
                related_name="release_plans",
                to="testcase.testcase",
                verbose_name="关联测试用例",
            ),
        ),
    ]
