# Generated by Django 4.2.20 on 2026-04-14 05:37

from django.db import migrations, models
import django.db.models.deletion


def _forwards_copy_releaseplan_test_cases(apps, schema_editor):
    """
    将旧 M2M 自动中间表的数据复制到新 through 表中。

    说明：
    - 旧表为 Django 自动生成的 M2M 表（在本迁移中 AlterField 之前仍存在）。
    - 新表为 release_plan_test_case（ReleasePlanTestCase）。
    """
    ReleasePlan = apps.get_model("project", "ReleasePlan")
    ReleasePlanTestCase = apps.get_model("project", "ReleasePlanTestCase")

    old_through = ReleasePlan._meta.get_field("test_cases").remote_field.through
    old_db_table = old_through._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"SELECT releaseplan_id, testcase_id FROM {old_db_table}")
        rows = cursor.fetchall()

    existing = set(
        ReleasePlanTestCase.objects.values_list("release_plan_id", "test_case_id")
    )
    to_create = []
    for release_plan_id, test_case_id in rows:
        key = (release_plan_id, test_case_id)
        if key in existing:
            continue
        to_create.append(
            ReleasePlanTestCase(
                release_plan_id=release_plan_id,
                test_case_id=test_case_id,
                is_deleted=False,
            )
        )
    if to_create:
        ReleasePlanTestCase.objects.bulk_create(to_create, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("testcase", "0025_normalize_apitestcase_api_body"),
        ("project", "0006_releaseplan_test_cases"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "CREATE TABLE IF NOT EXISTS release_plan_test_case ("
                        "id bigint AUTO_INCREMENT PRIMARY KEY, "
                        "create_time datetime(6) NOT NULL, "
                        "update_time datetime(6) NOT NULL, "
                        "is_deleted bool NOT NULL, "
                        "release_plan_id bigint NOT NULL, "
                        "test_case_id bigint NOT NULL"
                        ")"
                    ),
                    reverse_sql="DROP TABLE IF EXISTS release_plan_test_case",
                )
            ],
            state_operations=[
                migrations.CreateModel(
                    name="ReleasePlanTestCase",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "create_time",
                            models.DateTimeField(
                                auto_now_add=True, verbose_name="创建时间"
                            ),
                        ),
                        (
                            "update_time",
                            models.DateTimeField(
                                auto_now=True, verbose_name="更新时间"
                            ),
                        ),
                        (
                            "is_deleted",
                            models.BooleanField(
                                default=False, verbose_name="是否已删除"
                            ),
                        ),
                        (
                            "release_plan",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="release_plan_test_cases",
                                to="project.releaseplan",
                            ),
                        ),
                        (
                            "test_case",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="release_plan_test_cases",
                                to="testcase.testcase",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "release_plan_test_case",
                    },
                )
            ],
        ),
        migrations.AddConstraint(
            model_name="releaseplan",
            constraint=models.UniqueConstraint(
                fields=("project", "version_no", "is_deleted"),
                name="uniq_releaseplan_version_per_project_deletedflag",
            ),
        ),
        migrations.RunPython(
            code=_forwards_copy_releaseplan_test_cases,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="releaseplan",
            name="test_cases",
            field=models.ManyToManyField(
                blank=True,
                related_name="release_plans",
                through="project.ReleasePlanTestCase",
                to="testcase.testcase",
                verbose_name="关联测试用例",
            ),
        ),
        migrations.AddConstraint(
            model_name="releaseplantestcase",
            constraint=models.UniqueConstraint(
                fields=("release_plan", "test_case", "is_deleted"),
                name="uniq_releaseplan_testcase_deletedflag",
            ),
        ),
    ]
