#!/usr/bin/env bash

# ---------------------------------------------------------------------------
# optimize_env.sh
# ---------------------------------------------------------------------------
# This script prepares the execution environment for CI/CD pipelines on a
# low‑memory server (2 CPU / 2 GiB RAM).
#
# 1. Ensure a 4 GiB swap file exists. If not, it creates, configures and
#    activates it. The swap file is placed at /swapfile and persisted via
#    /etc/fstab.
# 2. Provide a clean‑up routine that removes temporary build artefacts while
#    preserving the node_modules cache (commonly large and reusable).
# ---------------------------------------------------------------------------

set -euo pipefail

SWAPFILE="/swapfile"
SWAPSIZE="4G"

# ---------- Swap creation ----------------------------------------------------
if ! swapon --show | grep -q "${SWAPFILE}"; then
    echo "Creating ${SWAPSIZE} swap at ${SWAPFILE}..."
    # Allocate swap file (use fallocate when available, fallback to dd)
    if command -v fallocate >/dev/null 2>&1; then
        fallocate -l ${SWAPSIZE} ${SWAPFILE}
    else
        dd if=/dev/zero of=${SWAPFILE} bs=1M count=$((4 * 1024))
    fi
    chmod 600 ${SWAPFILE}
    mkswap ${SWAPFILE}
    swapon ${SWAPFILE}
    # Ensure persistence across reboots
    if ! grep -qs "${SWAPFILE}" /etc/fstab; then
        echo "${SWAPFILE} none swap sw 0 0" >> /etc/fstab
    fi
    echo "Swap created and enabled."
else
    echo "Swap ${SWAPFILE} already active."
fi

# ---------- Clean‑up routine -------------------------------------------------
cleanup_build_artifacts() {
    # Delete temporary files and directories generated by builds, but keep
    # any node_modules directory (it holds cached dependencies).
    # This function is intended to be called from the pipeline script after a
    # job finishes.
    local PROJECT_ROOT="${1:-$(pwd)}"
    echo "Cleaning temporary build artefacts in ${PROJECT_ROOT}..."
    # Common temporary directories – adjust as needed for the project.
    local TMP_DIRS=("dist" "build" "tmp" "coverage" "__pycache__" ".cache")
    for d in "${TMP_DIRS[@]}"; do
        local TARGET="${PROJECT_ROOT}/${d}"
        if [ -d "${TARGET}" ]; then
            echo "Removing ${TARGET}"
            rm -rf "${TARGET}"
        fi
    done
    # Remove any stray files matching typical build artefacts (e.g., *.log,
    # *.tmp) while preserving node_modules.
    find "${PROJECT_ROOT}" -type f \( -name "*.log" -o -name "*.tmp" \) -delete
    echo "Clean‑up complete."
}

# If the script is sourced, expose the function; otherwise execute clean‑up.
if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
    export -f cleanup_build_artifacts
else
    # When run directly, perform clean‑up for the current directory.
    cleanup_build_artifacts "${PWD}"
fi
