# Generated by Django 4.2.30 on 2026-04-09 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("template", "用例模板"),
                            ("best_practice", "最佳实践"),
                            ("faq", "FAQ"),
                        ],
                        default="template",
                        max_length=32,
                        verbose_name="分类",
                    ),
                ),
                ("markdown_content", models.TextField(verbose_name="Markdown内容")),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="标签")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "db_table": "knowledge_article",
                "ordering": ("-create_time",),
            },
        ),
        migrations.AddIndex(
            model_name="knowledgearticle",
            index=models.Index(
                fields=["category", "-create_time"],
                name="knowledge_a_categor_83ae07_idx",
            ),
        ),
    ]
