# Generated by Django 4.2.30 on 2026-04-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0001_knowledgearticle"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="knowledgearticle",
            new_name="knowledge_a_categor_bd88af_idx",
            old_name="knowledge_a_categor_83ae07_idx",
        ),
    ]
