# Generated by Django 4.2.20 on 2026-04-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0003_knowledgedocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgearticle",
            name="category",
            field=models.CharField(
                choices=[
                    ("template", "用例模板"),
                    ("best_practice", "最佳实践"),
                    ("faq", "FAQ"),
                    ("functional_test", "功能测试"),
                    ("api_test", "接口测试"),
                    ("performance_test", "性能测试"),
                    ("security_test", "安全测试"),
                    ("ui_automation_test", "UI自动化"),
                ],
                default="template",
                max_length=32,
                verbose_name="分类",
            ),
        ),
    ]
