# Generated by Django 4.2.20 on 2026-04-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0004_alter_knowledgearticle_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgedocument",
            name="error_message",
            field=models.TextField(blank=True, default="", verbose_name="失败原因"),
        ),
    ]
