# Generated by Django 4.2.20 on 2026-04-09 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0005_knowledgedocument_error_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgedocument",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ingest_docs",
                to="assistant.knowledgearticle",
                verbose_name="关联文章",
            ),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="source_type",
            field=models.CharField(
                choices=[("upload", "上传文档"), ("article", "知识文章")],
                default="upload",
                max_length=16,
                verbose_name="来源类型",
            ),
        ),
        migrations.AlterField(
            model_name="knowledgedocument",
            name="file_path",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="knowledge_documents/",
                verbose_name="文件路径",
            ),
        ),
    ]
