# Generated by Django 4.2.20 on 2026-04-10 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testcase", "0023_testenvironment_health_check_path"),
        ("assistant", "0006_knowledgedocument_article_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgedocument",
            name="document_type",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("md", "MD"), ("url", "URL")],
                default="md",
                max_length=16,
                verbose_name="文档类型",
            ),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="file_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="文件名"
            ),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="knowledge_documents",
                to="testcase.testmodule",
                verbose_name="模块分类（测试模块）",
            ),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="source_url",
            field=models.URLField(
                blank=True, default="", max_length=2000, verbose_name="URL 来源地址"
            ),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="vector_db_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=255,
                verbose_name="向量数据库ID",
            ),
        ),
    ]
