# Generated by Django 4.2.20 on 2026-04-15 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assistant", "0008_knowledgedocument_semantic_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiUsageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("generate_cases", "生成用例（同步）"),
                            ("generate_cases_stream", "生成用例（流式）"),
                            ("phase1_preview", "Phase1 预览"),
                            ("test_connection", "模型连通性测试"),
                            ("verify_connection", "固定模型连通性校验"),
                            ("knowledge_autofill", "知识库自动填表"),
                        ],
                        db_index=True,
                        max_length=64,
                        verbose_name="动作",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="接口路径"
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否成功"
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(default=0, verbose_name="HTTP 状态码"),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="错误码（可选）",
                    ),
                ),
                (
                    "error_message",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="错误摘要（脱敏）",
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="模型名"
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="测试类型（可选）",
                    ),
                ),
                (
                    "module_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="模块ID（可选）",
                    ),
                ),
                (
                    "streamed",
                    models.BooleanField(default=False, verbose_name="是否流式"),
                ),
                (
                    "all_covered",
                    models.BooleanField(default=False, verbose_name="是否判定无需生成"),
                ),
                ("latency_ms", models.IntegerField(default=0, verbose_name="耗时(ms)")),
                (
                    "prompt_chars",
                    models.IntegerField(default=0, verbose_name="输入字符数"),
                ),
                (
                    "output_chars",
                    models.IntegerField(default=0, verbose_name="输出字符数"),
                ),
                (
                    "cases_count",
                    models.IntegerField(default=0, verbose_name="生成用例条数（可选）"),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="元信息（脱敏）"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="调用用户",
                    ),
                ),
            ],
            options={
                "db_table": "ai_usage_event",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"],
                        name="ai_usage_ev_action_1aba5b_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="ai_usage_ev_user_id_b7b075_idx",
                    ),
                ],
            },
        ),
    ]
