# Generated by Django 4.2.20 on 2026-04-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0010_aicasegenerationrun"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aicasegenerationrun",
            new_name="ai_case_gen_action_0a8747_idx",
            old_name="ai_case_ge_action_efc1e8_idx",
        ),
        migrations.RenameIndex(
            model_name="aicasegenerationrun",
            new_name="ai_case_gen_test_ty_ee691e_idx",
            old_name="ai_case_ge_test_ty_9f6b2f_idx",
        ),
        migrations.RenameIndex(
            model_name="aicasegenerationrun",
            new_name="ai_case_gen_user_id_3c73ab_idx",
            old_name="ai_case_ge_user_id_9d3e67_idx",
        ),
        migrations.RenameIndex(
            model_name="aicasegenerationrun",
            new_name="ai_case_gen_module__feecd9_idx",
            old_name="ai_case_ge_module__c8b8ea_idx",
        ),
    ]
