# Generated by Django 4.2.20 on 2026-04-16 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "assistant",
            "0011_rename_ai_case_ge_action_efc1e8_idx_ai_case_gen_action_0a8747_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AiPatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        verbose_name="目标类型（app.Model）",
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="目标ID"
                    ),
                ),
                (
                    "source_execution_log_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="来源执行日志ID（可选）",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("applied", "已应用"),
                            ("rolled_back", "已回滚"),
                            ("cancelled", "已取消"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=32,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[("low", "低"), ("medium", "中"), ("high", "高")],
                        db_index=True,
                        default="medium",
                        max_length=16,
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, default="", max_length=512, verbose_name="摘要"
                    ),
                ),
                (
                    "risks",
                    models.CharField(
                        blank=True, default="", max_length=1000, verbose_name="风险说明"
                    ),
                ),
                (
                    "before",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="应用前快照（最小）"
                    ),
                ),
                (
                    "after",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="应用后目标（最小）"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="变更描述（结构化）"
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "rolled_back_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_patches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "db_table": "ai_patch",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id", "-created_at"],
                        name="ai_patch_target__8f2005_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="ai_patch_status_546067_idx",
                    ),
                ],
            },
        ),
    ]
