# Generated by Django 4.2.20 on 2026-04-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0012_aipatch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiusageevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("generate_cases", "生成用例（同步）"),
                    ("generate_cases_stream", "生成用例（流式）"),
                    ("phase1_preview", "Phase1 预览"),
                    ("test_connection", "模型连通性测试"),
                    ("verify_connection", "固定模型连通性校验"),
                    ("knowledge_autofill", "知识库自动填表"),
                    ("knowledge_ask", "知识库问答（可追溯）"),
                    ("security_generate", "安全用例生成（规则）"),
                    ("security_analyze", "执行安全分析（规则）"),
                ],
                db_index=True,
                max_length=64,
                verbose_name="动作",
            ),
        ),
    ]
