# Generated by Django 4.2.30 on 2026-04-29 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_releaseplantestcase_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assistant", "0015_generatedtestartifact"),
    ]

    operations = [
        migrations.CreateModel(
            name="UIActionStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                ("sequence", models.IntegerField(verbose_name="执行顺序")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("click", "点击"),
                            ("input", "输入"),
                            ("assert", "断言"),
                            ("hover", "悬停"),
                            ("select", "选择"),
                            ("wait", "等待元素"),
                            ("sleep", "休眠"),
                            ("navigate", "导航"),
                            ("switch_window", "切换窗口"),
                            ("switch_frame", "切换Frame"),
                            ("scroll", "滚动"),
                            ("execute_js", "执行JS"),
                        ],
                        max_length=32,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "test_data",
                    models.TextField(blank=True, default="", verbose_name="测试数据"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="步骤描述"),
                ),
            ],
            options={
                "verbose_name": "UI操作步骤",
                "verbose_name_plural": "UI操作步骤",
                "db_table": "ui_action_step",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="UIModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="模块名称")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="模块描述"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序序号")),
            ],
            options={
                "verbose_name": "UI模块",
                "verbose_name_plural": "UI模块",
                "db_table": "ui_module",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="UIPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="页面名称")),
                (
                    "url",
                    models.CharField(
                        blank=True, default="", max_length=512, verbose_name="页面URL"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="页面描述"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序序号")),
            ],
            options={
                "verbose_name": "UI页面",
                "verbose_name_plural": "UI页面",
                "db_table": "ui_page",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="UIPageElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="元素名称")),
                (
                    "locator_type",
                    models.CharField(
                        choices=[
                            ("id", "ID"),
                            ("name", "Name"),
                            ("xpath", "XPath"),
                            ("css", "CSS Selector"),
                            ("class", "Class Name"),
                            ("tag", "Tag Name"),
                            ("link_text", "Link Text"),
                            ("partial_link_text", "Partial Link Text"),
                        ],
                        default="xpath",
                        max_length=32,
                        verbose_name="定位方式",
                    ),
                ),
                ("locator_value", models.TextField(verbose_name="定位表达式")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="元素描述"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序序号")),
            ],
            options={
                "verbose_name": "UI页面元素",
                "verbose_name_plural": "UI页面元素",
                "db_table": "ui_page_element",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="UITestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="用例名称")),
                (
                    "preconditions",
                    models.TextField(blank=True, default="", verbose_name="前置条件"),
                ),
                (
                    "expected_result",
                    models.TextField(blank=True, default="", verbose_name="预期结果"),
                ),
                ("priority", models.IntegerField(default=2, verbose_name="优先级")),
                ("order", models.IntegerField(default=0, verbose_name="排序序号")),
            ],
            options={
                "verbose_name": "UI测试用例",
                "verbose_name_plural": "UI测试用例",
                "db_table": "ui_test_case",
                "ordering": ["order", "id"],
            },
        ),
        migrations.RenameIndex(
            model_name="generatedtestartifact",
            new_name="generated_t_artifac_0362e9_idx",
            old_name="generated_t_artifact_0f4d2f_idx",
        ),
        migrations.RenameIndex(
            model_name="generatedtestartifact",
            new_name="generated_t_project_955e29_idx",
            old_name="generated_t_project_1f3b0c_idx",
        ),
        migrations.RenameIndex(
            model_name="generatedtestartifact",
            new_name="generated_t_module__50e335_idx",
            old_name="generated_t_module_cdd3d9_idx",
        ),
        migrations.RenameIndex(
            model_name="generatedtestartifact",
            new_name="generated_t_source__70d856_idx",
            old_name="generated_t_source_d_64b2fe_idx",
        ),
        migrations.AlterField(
            model_name="generatedtestartifact",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="generatedtestartifact",
            name="updater",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddField(
            model_name="uitestcase",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="uitestcase",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_cases",
                to="assistant.uimodule",
                verbose_name="所属模块",
            ),
        ),
        migrations.AddField(
            model_name="uitestcase",
            name="updater",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddField(
            model_name="uipageelement",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="uipageelement",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="assistant.uipage",
                verbose_name="所属页面",
            ),
        ),
        migrations.AddField(
            model_name="uipageelement",
            name="updater",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddField(
            model_name="uipage",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="uipage",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="assistant.uimodule",
                verbose_name="所属模块",
            ),
        ),
        migrations.AddField(
            model_name="uipage",
            name="updater",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddField(
            model_name="uimodule",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="uimodule",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="assistant.uimodule",
                verbose_name="父模块",
            ),
        ),
        migrations.AddField(
            model_name="uimodule",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ui_modules",
                to="project.testproject",
                verbose_name="所属项目",
            ),
        ),
        migrations.AddField(
            model_name="uimodule",
            name="updater",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddField(
            model_name="uiactionstep",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="uiactionstep",
            name="element",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_steps",
                to="assistant.uipageelement",
                verbose_name="关联元素",
            ),
        ),
        migrations.AddField(
            model_name="uiactionstep",
            name="test_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_steps",
                to="assistant.uitestcase",
                verbose_name="所属测试用例",
            ),
        ),
        migrations.AddField(
            model_name="uiactionstep",
            name="updater",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddIndex(
            model_name="uitestcase",
            index=models.Index(
                fields=["module", "order"], name="ui_test_cas_module__42b2d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uipageelement",
            index=models.Index(
                fields=["page", "order"], name="ui_page_ele_page_id_8efd1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uipageelement",
            index=models.Index(fields=["name"], name="ui_page_ele_name_365317_idx"),
        ),
        migrations.AddIndex(
            model_name="uipage",
            index=models.Index(
                fields=["module", "order"], name="ui_page_module__50534b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uimodule",
            index=models.Index(
                fields=["project", "parent"], name="ui_module_project_7a3171_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uiactionstep",
            index=models.Index(
                fields=["test_case", "sequence"], name="ui_action_s_test_ca_957a86_idx"
            ),
        ),
    ]
