# Generated by Django 4.2.30 on 2026-04-30 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0016_uiactionstep_uimodule_uipage_uipageelement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UIScriptUpload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="脚本ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="脚本的显示名称",
                        max_length=255,
                        verbose_name="脚本名称",
                    ),
                ),
                (
                    "script_type",
                    models.CharField(
                        choices=[("LINEAR", "线性脚本"), ("POM", "Page Object Model")],
                        default="LINEAR",
                        max_length=10,
                        verbose_name="脚本类型",
                    ),
                ),
                (
                    "file_path",
                    models.FileField(
                        help_text="单文件(.py)或ZIP包",
                        upload_to="ui_scripts/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["py", "zip"]
                            )
                        ],
                        verbose_name="脚本文件",
                    ),
                ),
                (
                    "git_repo_url",
                    models.URLField(
                        blank=True,
                        help_text="关联的Git仓库地址（可选）",
                        max_length=500,
                        null=True,
                        verbose_name="Git仓库URL",
                    ),
                ),
                (
                    "entry_point",
                    models.CharField(
                        help_text="脚本执行的入口文件路径，如: main.py 或 tests/test_login.py",
                        max_length=500,
                        verbose_name="执行入口路径",
                    ),
                ),
                (
                    "workspace_path",
                    models.CharField(
                        blank=True,
                        help_text="ZIP解压后的目录路径",
                        max_length=500,
                        null=True,
                        verbose_name="工作空间路径",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
            ],
            options={
                "verbose_name": "UI自动化脚本",
                "verbose_name_plural": "UI自动化脚本",
                "db_table": "ui_script_upload",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["script_type"], name="ui_script_u_script__a70866_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="ui_script_u_created_762a44_idx"
                    ),
                ],
            },
        ),
    ]
