# Generated by Django 4.2.30 on 2026-05-01 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0017_uiscriptupload"),
    ]

    operations = [
        migrations.CreateModel(
            name="UIScriptExecution",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="执行ID"
                    ),
                ),
                (
                    "execution_id",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="执行唯一标识",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待执行"),
                            ("running", "执行中"),
                            ("success", "执行成功"),
                            ("failed", "执行失败"),
                            ("timeout", "执行超时"),
                            ("cancelled", "已取消"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "return_code",
                    models.IntegerField(blank=True, null=True, verbose_name="返回码"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True, null=True, verbose_name="执行时长(秒)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "log_file_path",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="日志文件路径",
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="触发方式"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="assistant.uiscriptupload",
                        verbose_name="关联脚本",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI脚本执行记录",
                "verbose_name_plural": "UI脚本执行记录",
                "db_table": "ui_script_execution",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["execution_id"], name="ui_script_e_executi_495b73_idx"
                    ),
                    models.Index(
                        fields=["script", "-created_at"],
                        name="ui_script_e_script__76d9ab_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="ui_script_e_status_d21696_idx",
                    ),
                ],
            },
        ),
    ]
