# Generated by Django 4.2.30 on 2026-05-01 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0018_uiscriptexecution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uiscriptupload",
            name="entry_point",
            field=models.CharField(
                blank=True,
                help_text="脚本执行的入口文件路径，如: main.py 或 tests/test_login.py",
                max_length=500,
                null=True,
                verbose_name="执行入口路径",
            ),
        ),
        migrations.AlterField(
            model_name="uiscriptupload",
            name="file_path",
            field=models.FileField(
                blank=True,
                help_text="单文件(.py)或ZIP包",
                null=True,
                upload_to="ui_scripts/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["py", "zip"]
                    )
                ],
                verbose_name="脚本文件",
            ),
        ),
    ]
