# Generated by Django 4.2.30 on 2026-05-01 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0019_alter_uiscriptupload_entry_point_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uiscriptupload",
            name="build_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Maven/Gradle等构建工具配置",
                verbose_name="构建配置",
            ),
        ),
        migrations.AddField(
            model_name="uiscriptupload",
            name="dependencies",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="存储requirements.txt或pom.xml等依赖信息",
                verbose_name="依赖配置",
            ),
        ),
        migrations.AddField(
            model_name="uiscriptupload",
            name="framework",
            field=models.CharField(
                choices=[
                    ("PYTEST", "Pytest"),
                    ("UNITTEST", "Unittest"),
                    ("NOSE", "Nose"),
                    ("ROBOT", "Robot Framework"),
                    ("BEHAVE", "Behave"),
                    ("JUNIT4", "JUnit 4"),
                    ("JUNIT5", "JUnit 5"),
                    ("TESTNG", "TestNG"),
                    ("CUCUMBER", "Cucumber"),
                    ("SPOCK", "Spock"),
                    ("AUTO", "自动检测"),
                ],
                default="AUTO",
                help_text="测试框架类型，AUTO表示自动检测",
                max_length=20,
                verbose_name="测试框架",
            ),
        ),
        migrations.AddField(
            model_name="uiscriptupload",
            name="language",
            field=models.CharField(
                choices=[("PYTHON", "Python"), ("JAVA", "Java")],
                default="PYTHON",
                max_length=10,
                verbose_name="脚本语言",
            ),
        ),
        migrations.AddField(
            model_name="uiscriptupload",
            name="online_content",
            field=models.TextField(
                blank=True,
                help_text="在线编辑的脚本代码",
                null=True,
                verbose_name="在线脚本内容",
            ),
        ),
        migrations.AlterField(
            model_name="uiscriptupload",
            name="file_path",
            field=models.FileField(
                blank=True,
                help_text="单文件(.py/.jar)或ZIP包",
                null=True,
                upload_to="ui_scripts/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["py", "zip", "jar"]
                    )
                ],
                verbose_name="脚本文件",
            ),
        ),
        migrations.AlterField(
            model_name="uiscriptupload",
            name="script_type",
            field=models.CharField(
                choices=[
                    ("LINEAR", "线性脚本"),
                    ("POM", "Page Object Model"),
                    ("ONLINE", "在线脚本"),
                ],
                default="LINEAR",
                max_length=10,
                verbose_name="脚本类型",
            ),
        ),
    ]
