# Generated by Django 4.2.30 on 2026-05-01 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0021_add_folder_and_trash"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="uiscriptupload",
            new_name="ui_script_u_folder_5ca59e_idx",
            old_name="ui_script_folder_idx",
        ),
    ]
