# Generated by Django 4.2.30 on 2026-05-03 02:39

import assistant.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0022_rename_ui_script_folder_idx_ui_script_u_folder_5ca59e_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="UIPomTestReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="报告标题")),
                (
                    "source_relative_path",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="工作空间内原始相对路径",
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        max_length=500,
                        upload_to=assistant.models._ui_pom_report_upload_to,
                        verbose_name="归档报告文件",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="文件大小(字节)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="归档时间"),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pom_reports",
                        to="assistant.uiscriptexecution",
                        verbose_name="关联执行记录",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pom_reports",
                        to="assistant.uiscriptupload",
                        verbose_name="关联脚本",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI POM 测试报告",
                "verbose_name_plural": "UI POM 测试报告",
                "db_table": "ui_pom_test_report",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["script", "-created_at"],
                        name="ui_pom_test_script__5b61d5_idx",
                    ),
                    models.Index(
                        fields=["execution"], name="ui_pom_test_executi_5de984_idx"
                    ),
                ],
            },
        ),
    ]
