# Generated by Django 4.2

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0024_uipomtestreport_soft_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uiscriptupload",
            name="file_path",
            field=models.FileField(
                blank=True,
                help_text="Python：.py / .zip；Java：.java 线性、.jar 可执行包、或含 pom.xml/build.gradle 的 ZIP",
                null=True,
                upload_to="ui_scripts/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["py", "zip", "jar", "java"]
                    )
                ],
                verbose_name="脚本文件",
            ),
        ),
    ]
