# Generated by Django 4.2.30 on 2026-05-12 13:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0011_buildrecord_log_key_duration"),
        ("assistant", "0025_alter_uiscriptupload_file_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uipomtestreport",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="uipomtestreport",
            name="is_deleted",
        ),
        migrations.AlterField(
            model_name="uiscriptupload",
            name="file_path",
            field=models.FileField(
                blank=True,
                help_text="单文件(.py/.jar)或ZIP包",
                null=True,
                upload_to="ui_scripts/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["py", "zip", "jar"]
                    )
                ],
                verbose_name="脚本文件",
            ),
        ),
        migrations.CreateModel(
            name="KWTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="用例名称")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="用例描述"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("ready", "就绪"),
                            ("deprecated", "已废弃"),
                        ],
                        default="draft",
                        max_length=16,
                        verbose_name="用例状态",
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True, default="", max_length=512, verbose_name="基础URL"
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="用例级变量"
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveIntegerField(
                        default=300, verbose_name="超时时间(秒)"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kw_test_cases",
                        to="project.testproject",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "关键字驱动用例",
                "verbose_name_plural": "关键字驱动用例",
                "db_table": "kw_ui_test_case",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="KWElementLocator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="元素名称")),
                (
                    "locator_type",
                    models.CharField(
                        choices=[
                            ("id", "ID"),
                            ("name", "Name"),
                            ("xpath", "XPath"),
                            ("css_selector", "CSS Selector"),
                            ("class_name", "Class Name"),
                            ("tag_name", "Tag Name"),
                            ("link_text", "Link Text"),
                            ("partial_link_text", "Partial Link Text"),
                        ],
                        default="xpath",
                        max_length=32,
                        verbose_name="定位方式",
                    ),
                ),
                (
                    "locator_expression",
                    models.CharField(max_length=255, verbose_name="定位表达式"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kw_element_locators",
                        to="project.testproject",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "UI元素定位器(KW)",
                "verbose_name_plural": "UI元素定位器(KW)",
                "db_table": "kw_ui_element_locator",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="KWActionStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                ("step_order", models.PositiveIntegerField(verbose_name="步骤序号")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("click", "点击"),
                            ("input", "输入"),
                            ("assert", "断言"),
                            ("hover", "悬停"),
                            ("select", "选择"),
                            ("wait", "等待元素"),
                            ("sleep", "休眠"),
                            ("navigate", "导航"),
                            ("switch_window", "切换窗口"),
                            ("switch_frame", "切换Frame"),
                            ("scroll", "滚动"),
                            ("execute_js", "执行JS"),
                        ],
                        max_length=32,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "action_value",
                    models.TextField(blank=True, default="", verbose_name="操作值"),
                ),
                (
                    "assert_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("visible", "元素可见"),
                            ("not_visible", "元素不可见"),
                            ("text_equals", "文本相等"),
                            ("text_contains", "文本包含"),
                            ("attribute_equals", "属性相等"),
                            ("url_contains", "URL包含"),
                            ("title_contains", "标题包含"),
                            ("element_count", "元素数量"),
                        ],
                        default="",
                        max_length=32,
                        verbose_name="断言类型",
                    ),
                ),
                (
                    "assert_expected",
                    models.TextField(blank=True, default="", verbose_name="断言期望值"),
                ),
                (
                    "test_data",
                    models.JSONField(blank=True, default=dict, verbose_name="测试数据"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="步骤描述"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "element",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referencing_steps",
                        to="assistant.kwelementlocator",
                        verbose_name="关联元素",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="assistant.kwtestcase",
                        verbose_name="所属测试用例",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "关键字驱动步骤",
                "verbose_name_plural": "关键字驱动步骤",
                "db_table": "kw_ui_action_step",
                "ordering": ["step_order"],
            },
        ),
        migrations.AddIndex(
            model_name="kwtestcase",
            index=models.Index(
                fields=["project", "status"], name="idx_kw_tc_proj_status"
            ),
        ),
        migrations.AddIndex(
            model_name="kwelementlocator",
            index=models.Index(
                fields=["project", "locator_type"], name="idx_kw_loc_proj_type"
            ),
        ),
        migrations.AddIndex(
            model_name="kwelementlocator",
            index=models.Index(fields=["name"], name="idx_kw_loc_name"),
        ),
        migrations.AlterUniqueTogether(
            name="kwelementlocator",
            unique_together={("project", "name")},
        ),
        migrations.AddIndex(
            model_name="kwactionstep",
            index=models.Index(
                fields=["test_case", "step_order"], name="idx_kw_step_case_order"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="kwactionstep",
            unique_together={("test_case", "step_order")},
        ),
    ]
