# Generated by Django 4.2.20 on 2026-04-03 02:55

from django.db import migrations, models


def promote_jason_admin(apps, schema_editor):
    User = apps.get_model("user", "User")
    User.objects.filter(username__iexact="jason").update(is_system_admin=True)


def noop_reverse(apps, schema_editor):
    User = apps.get_model("user", "User")
    User.objects.filter(username__iexact="jason").update(is_system_admin=False)


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_systemmessagesetting_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_system_admin",
            field=models.BooleanField(
                default=False,
                help_text="可访问组织/角色/用户管理；普通用户仅可消息设置",
                verbose_name="系统管理员",
            ),
        ),
        migrations.RunPython(promote_jason_admin, noop_reverse),
    ]
