# Generated by Django 4.2

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_is_system_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=32,
                verbose_name="手机号",
            ),
        ),
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="user_avatars/%Y/%m/",
                verbose_name="头像",
            ),
        ),
        migrations.CreateModel(
            name="UserChangeRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("username", "用户名"),
                            ("password", "密码"),
                        ],
                        max_length=16,
                        verbose_name="申请类型",
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        verbose_name="新值（用户名为明文；密码为哈希字符串）",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审批"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请人",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户敏感信息变更申请",
                "db_table": "sys_user_change_request",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="userchangerequest",
            index=models.Index(
                fields=["status", "-created_at"],
                name="sys_user_cha_status_0b42dc_idx",
            ),
        ),
    ]
