# Generated by Django 4.2.20 on 2026-04-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_systemmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIModelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(max_length=64, verbose_name="模型标识"),
                ),
                ("api_key", models.TextField(verbose_name="API Key")),
                (
                    "base_url",
                    models.CharField(
                        blank=True, default="", max_length=512, verbose_name="Base URL"
                    ),
                ),
                (
                    "is_connected",
                    models.BooleanField(default=True, verbose_name="是否处于连接状态"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "AI 模型配置",
                "db_table": "sys_ai_model_config",
            },
        ),
        migrations.RenameIndex(
            model_name="systemmessage",
            new_name="sys_system__recipie_335225_idx",
            old_name="sys_system__recipie_f99508_idx",
        ),
        migrations.RenameIndex(
            model_name="systemmessage",
            new_name="sys_system__recipie_c1f849_idx",
            old_name="sys_system__recipie_7b0fcb_idx",
        ),
        migrations.RenameIndex(
            model_name="userchangerequest",
            new_name="sys_user_ch_status_7d42ff_idx",
            old_name="sys_user_cha_status_0b42dc_idx",
        ),
    ]
