# Generated by Django 4.2.30 on 2026-04-14 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_releaseplantestcase_and_more"),
        ("user", "0008_organization_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodelconfig",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_configs",
                to="project.testproject",
                verbose_name="所属项目",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="projects",
            field=models.ManyToManyField(
                blank=True,
                related_name="organizations",
                to="project.testproject",
                verbose_name="关联项目",
            ),
        ),
        migrations.AddField(
            model_name="systemmessagesetting",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_settings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="所属用户",
            ),
        ),
        migrations.AddField(
            model_name="userchangerequest",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="审批时间"),
        ),
        migrations.AddField(
            model_name="userchangerequest",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_change_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审批人",
            ),
        ),
        migrations.AddConstraint(
            model_name="aimodelconfig",
            constraint=models.UniqueConstraint(
                fields=("project", "model_type"),
                name="uniq_ai_model_config_per_project_model",
            ),
        ),
        migrations.AddConstraint(
            model_name="systemmessagesetting",
            constraint=models.UniqueConstraint(
                fields=("recipient",), name="unique_user_message_setting"
            ),
        ),
    ]
