# Generated by Django 4.2.20 on 2026-04-16 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_releaseplantestcase_and_more"),
        ("user", "0009_aimodelconfig_project_organization_projects_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiQuotaPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("project", "项目"),
                            ("org", "组织"),
                            ("user", "用户"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "daily_requests",
                    models.PositiveIntegerField(
                        default=0, verbose_name="每日调用上限(0=不限制)"
                    ),
                ),
                (
                    "max_concurrency",
                    models.PositiveIntegerField(
                        default=0, verbose_name="最大并发(0=不限制)"
                    ),
                ),
                (
                    "concurrency_ttl_seconds",
                    models.PositiveIntegerField(
                        default=180, verbose_name="并发槽 TTL(秒)"
                    ),
                ),
                (
                    "allowed_actions",
                    models.JSONField(
                        blank=True, default=list, verbose_name="允许/生效的 action 列表"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="备注"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_quota_policies",
                        to="user.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_quota_policies",
                        to="project.testproject",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_quota_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_quota_policy",
                "indexes": [
                    models.Index(
                        fields=["scope_type", "is_enabled", "-create_time"],
                        name="ai_quota_po_scope_t_c0cb2a_idx",
                    ),
                    models.Index(
                        fields=["project", "is_enabled"],
                        name="ai_quota_po_project_eeffb1_idx",
                    ),
                    models.Index(
                        fields=["org", "is_enabled"],
                        name="ai_quota_po_org_id_d6ec0c_idx",
                    ),
                    models.Index(
                        fields=["user", "is_enabled"],
                        name="ai_quota_po_user_id_4b1529_idx",
                    ),
                ],
            },
        ),
    ]
