# Generated by Django 4.2.20 on 2026-04-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="逻辑删除标识"),
                ),
                (
                    "plan_name",
                    models.CharField(max_length=255, verbose_name="计划名称"),
                ),
                (
                    "iteration",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="迭代"
                    ),
                ),
                (
                    "environment",
                    models.CharField(max_length=255, verbose_name="测试环境"),
                ),
                ("req_count", models.IntegerField(default=0, verbose_name="需求数")),
                ("case_count", models.IntegerField(default=0, verbose_name="用例数")),
                (
                    "coverage_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="覆盖率",
                    ),
                ),
                (
                    "plan_status",
                    models.IntegerField(
                        choices=[(1, "未开始"), (2, "进行中"), (3, "已完成")],
                        default=1,
                        verbose_name="计划状态",
                    ),
                ),
                (
                    "pass_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="通过率",
                    ),
                ),
                ("defect_count", models.IntegerField(default=0, verbose_name="缺陷数")),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始日期"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束日期"
                    ),
                ),
            ],
            options={
                "db_table": "test_plan",
            },
        ),
        migrations.CreateModel(
            name="TestReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="逻辑删除标识"),
                ),
                (
                    "report_name",
                    models.CharField(max_length=255, verbose_name="报告名称"),
                ),
                (
                    "create_method",
                    models.IntegerField(
                        choices=[(1, "新建生成"), (2, "定期生成")],
                        default=1,
                        verbose_name="生成方式",
                    ),
                ),
                (
                    "environment",
                    models.CharField(max_length=255, verbose_name="测试环境"),
                ),
                ("req_count", models.IntegerField(default=0, verbose_name="需求数")),
                ("case_count", models.IntegerField(default=0, verbose_name="用例数")),
                (
                    "coverage_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="覆盖率",
                    ),
                ),
                (
                    "pass_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="通过率",
                    ),
                ),
                ("defect_count", models.IntegerField(default=0, verbose_name="缺陷数")),
                ("start_time", models.DateTimeField(verbose_name="统计开始时间")),
                ("end_time", models.DateTimeField(verbose_name="统计结束时间")),
            ],
            options={
                "db_table": "test_report",
            },
        ),
    ]
