# Generated by Django 4.2.20 on 2026-04-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0003_perftask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testreport",
            name="create_method",
            field=models.IntegerField(
                choices=[(1, "新建生成"), (2, "定期生成"), (3, "计划生成")],
                default=1,
                verbose_name="生成方式",
            ),
        ),
    ]
