# Generated by Django 4.2.20 on 2026-04-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0005_testreport_trace_execution_payloads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perftask",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除"),
        ),
        migrations.AlterField(
            model_name="testplan",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除"),
        ),
        migrations.AlterField(
            model_name="testreport",
            name="create_method",
            field=models.IntegerField(
                choices=[(1, "新建生成"), (2, "定期生成")],
                default=1,
                verbose_name="生成方式",
            ),
        ),
        migrations.AlterField(
            model_name="testreport",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除"),
        ),
    ]
