# Generated by Django 4.2.30 on 2026-04-09 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testcase", "0018_testenvironment_environmentvariable_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "execution",
            "0006_alter_perftask_is_deleted_alter_testplan_is_deleted_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                ("name", models.CharField(max_length=128, verbose_name="任务名称")),
                (
                    "cron_expression",
                    models.CharField(max_length=64, verbose_name="Cron 表达式"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "启用"),
                            ("paused", "暂停"),
                            ("disabled", "禁用"),
                        ],
                        default="active",
                        max_length=16,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="调度器任务ID"
                    ),
                ),
                (
                    "next_run_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="下次执行时间"
                    ),
                ),
                (
                    "last_run_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近执行时间"
                    ),
                ),
                (
                    "last_status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("partial", "部分成功"),
                            ("idle", "未执行"),
                        ],
                        default="idle",
                        max_length=16,
                        verbose_name="最近执行状态",
                    ),
                ),
                (
                    "last_message",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="最近执行摘要",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduled_tasks",
                        to="testcase.testenvironment",
                        verbose_name="执行环境",
                    ),
                ),
                (
                    "test_cases",
                    models.ManyToManyField(
                        blank=True,
                        related_name="scheduled_tasks",
                        to="testcase.testcase",
                        verbose_name="关联用例",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "db_table": "scheduled_task",
                "ordering": ("-create_time",),
            },
        ),
        migrations.CreateModel(
            name="ScheduledTaskLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                ("trigger_time", models.DateTimeField(verbose_name="触发时间")),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("partial", "部分成功"),
                        ],
                        default="running",
                        max_length=16,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="执行摘要"
                    ),
                ),
                (
                    "detail",
                    models.JSONField(blank=True, default=dict, verbose_name="执行明细"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "scheduled_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="execution.scheduledtask",
                        verbose_name="调度任务",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "db_table": "scheduled_task_log",
                "ordering": ("-create_time",),
            },
        ),
    ]
