# Generated by Django 4.2.30 on 2026-04-09 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("execution", "0007_scheduledtask_scheduledtasklog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                (
                    "task_name",
                    models.CharField(max_length=255, verbose_name="任务名称"),
                ),
                (
                    "method",
                    models.CharField(
                        default="GET", max_length=16, verbose_name="请求方法"
                    ),
                ),
                ("url", models.CharField(max_length=2048, verbose_name="请求URL")),
                (
                    "headers",
                    models.JSONField(blank=True, default=dict, verbose_name="请求头"),
                ),
                (
                    "body",
                    models.JSONField(blank=True, null=True, verbose_name="请求体"),
                ),
                (
                    "timeout_seconds",
                    models.PositiveIntegerField(
                        default=30, verbose_name="请求超时(秒)"
                    ),
                ),
                (
                    "expected_status",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="期望HTTP状态码"
                    ),
                ),
                (
                    "expected_body_contains",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=512,
                        verbose_name="期望响应体包含",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("completed", "执行完成"),
                            ("failed", "执行失败"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始执行时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束执行时间"
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="执行耗时(ms)"
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Celery任务ID",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "report",
                    models.JSONField(blank=True, default=dict, verbose_name="执行报告"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "db_table": "execution_task",
                "ordering": ("-create_time",),
            },
        ),
    ]
