# Generated by Django 4.2.30 on 2026-04-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0008_executiontask"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestQualityMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                ("metric_date", models.DateField(verbose_name="指标日期")),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("defect_density", "缺陷密度"),
                            ("pass_rate", "用例通过率"),
                            ("requirement_coverage", "需求覆盖率"),
                        ],
                        max_length=64,
                        verbose_name="指标类型",
                    ),
                ),
                (
                    "metric_value",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="指标值"
                    ),
                ),
                ("dimension", models.JSONField(blank=True, default=dict, verbose_name="维度信息")),
            ],
            options={
                "db_table": "test_quality_metric",
                "ordering": ("-metric_date", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="testqualitymetric",
            index=models.Index(
                fields=["metric_date", "metric_type"],
                name="test_qualit_metric__a06e6d_idx",
            ),
        ),
    ]
