# Generated by Django 4.2.30 on 2026-04-09 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("execution", "0010_testqualitymetric_creator_updater"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="testqualitymetric",
            new_name="test_qualit_metric__46ec22_idx",
            old_name="test_qualit_metric__a06e6d_idx",
        ),
        migrations.AlterField(
            model_name="testqualitymetric",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="testqualitymetric",
            name="updater",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
    ]
