# Generated by Django 4.2

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("execution", "0011_rename_test_qualit_metric__a06e6d_idx_test_qualit_metric__46ec22_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="K6LoadTestSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否已删除")),
                (
                    "run_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="运行 UUID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待开始"),
                            ("generating", "生成脚本中"),
                            ("running", "压测运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("test_case_ids", models.JSONField(default=list, verbose_name="API 用例 ID 列表(有序)")),
                ("vus", models.PositiveIntegerField(default=5, verbose_name="虚拟用户数")),
                ("duration", models.CharField(default="30s", max_length=32, verbose_name="持续时间(k6 格式)")),
                ("use_ai", models.BooleanField(default=True, verbose_name="是否使用大模型生成脚本")),
                (
                    "target_base_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="用于拼接相对路径的 API 地址；留空则要求用例中均为绝对 URL",
                        max_length=2048,
                        verbose_name="目标 Base URL",
                    ),
                ),
                (
                    "script_rel_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="相对于 MEDIA_ROOT 的 k6 脚本路径",
                        max_length=512,
                        verbose_name="脚本相对路径",
                    ),
                ),
                ("script_body", models.TextField(blank=True, default="", verbose_name="生成的脚本内容快照")),
                ("summary", models.JSONField(blank=True, null=True, verbose_name="k6 summary-export JSON")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="错误信息")),
                ("celery_task_id", models.CharField(blank=True, default="", max_length=64, verbose_name="Celery 任务 ID")),
                (
                    "generation_source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ai / template",
                        max_length=32,
                        verbose_name="脚本来源",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="k6loadtestsession_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="k6loadtestsession_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "K6 压测会话",
                "db_table": "k6_load_test_session",
                "ordering": ("-create_time",),
            },
        ),
    ]
