# Generated by Django 4.2.30 on 2026-04-16 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testcase", "0026_testcase_ai_run_fk"),
        ("project", "0007_releaseplantestcase_and_more"),
        ("execution", "0014_testreport_executiontask_add_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="场景名称")),
                (
                    "default_variables",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="场景级初始变量池（可在运行时 overrides 覆盖）",
                        verbose_name="默认变量上下文",
                    ),
                ),
                (
                    "failure_strategy",
                    models.CharField(
                        choices=[("abort", "失败中止"), ("continue", "失败继续")],
                        default="abort",
                        max_length=16,
                        verbose_name="失败策略",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_scenarios",
                        to="testcase.testenvironment",
                        verbose_name="默认执行环境",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_scenarios",
                        to="project.testproject",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "db_table": "api_scenario",
                "ordering": ("-create_time",),
            },
        ),
        migrations.CreateModel(
            name="ApiScenarioRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("partial", "部分失败"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="运行状态",
                    ),
                ),
                (
                    "trace_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=36,
                        verbose_name="trace_id",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="耗时(ms)"
                    ),
                ),
                (
                    "environment_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="testcase.TestEnvironment 主键（避免跨 app 迁移依赖）",
                        null=True,
                        verbose_name="执行环境ID(快照)",
                    ),
                ),
                (
                    "initial_variables",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="初始变量上下文快照"
                    ),
                ),
                (
                    "final_variables",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="最终变量上下文快照"
                    ),
                ),
                (
                    "summary",
                    models.JSONField(blank=True, default=dict, verbose_name="汇总"),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Celery 任务 ID",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="execution.apiscenario",
                        verbose_name="所属场景",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "db_table": "api_scenario_run",
                "ordering": ("-create_time",),
            },
        ),
        migrations.CreateModel(
            name="ApiScenarioStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                ("order", models.PositiveIntegerField(default=1, verbose_name="顺序")),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="步骤名称"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "failure_strategy",
                    models.CharField(
                        blank=True,
                        choices=[("abort", "失败中止"), ("continue", "失败继续")],
                        default="",
                        help_text="留空则继承场景 failure_strategy",
                        max_length=16,
                        verbose_name="失败策略(可选覆盖)",
                    ),
                ),
                (
                    "extraction_rules",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='示例: [{"var_name":"token","source":"body","expression":"$.data.token"}]',
                        verbose_name="变量提取规则",
                    ),
                ),
                (
                    "step_overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="可覆盖 url/method/headers/body/environment_id/variables/extraction_rules 等",
                        verbose_name="步骤执行覆盖参数",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="execution.apiscenario",
                        verbose_name="所属场景",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scenario_steps",
                        to="testcase.testcase",
                        verbose_name="关联用例",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "db_table": "api_scenario_step",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="ApiScenarioStepRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="顺序快照"),
                ),
                (
                    "test_case_id",
                    models.PositiveIntegerField(verbose_name="用例ID快照"),
                ),
                (
                    "execution_log_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="testcase.ExecutionLog 主键",
                        null=True,
                        verbose_name="关联 ExecutionLog ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "执行完成"),
                            ("failed", "执行失败"),
                            ("skipped", "已跳过"),
                        ],
                        default="completed",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("passed", models.BooleanField(default=False, verbose_name="是否通过")),
                (
                    "extracted_variables",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="本步骤提取出的变量"
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="摘要"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_runs",
                        to="execution.apiscenariorun",
                        verbose_name="所属运行",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="execution.apiscenariostep",
                        verbose_name="所属步骤",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "db_table": "api_scenario_step_run",
                "ordering": ("order", "id"),
                "indexes": [
                    models.Index(
                        fields=["run", "order"], name="api_scenari_run_id_d173ed_idx"
                    ),
                    models.Index(
                        fields=["test_case_id"], name="api_scenari_test_ca_249a7a_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="apiscenariostep",
            index=models.Index(
                fields=["scenario", "order"], name="api_scenari_scenari_7fd5ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiscenariostep",
            index=models.Index(
                fields=["test_case"], name="api_scenari_test_ca_73ed01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiscenariorun",
            index=models.Index(
                fields=["scenario", "-create_time"],
                name="api_scenari_scenari_1117a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apiscenariorun",
            index=models.Index(
                fields=["trace_id"], name="api_scenari_trace_i_4e0ad2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiscenario",
            index=models.Index(
                fields=["project", "-create_time"],
                name="api_scenari_project_3c2892_idx",
            ),
        ),
    ]
