# Generated by Django 4.2.20 on 2026-05-05 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(max_length=255, verbose_name="项目名"),
                ),
                (
                    "git_url",
                    models.URLField(max_length=512, verbose_name="Git 仓库 URL"),
                ),
                (
                    "branch_name",
                    models.CharField(max_length=255, verbose_name="分支名"),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=128,
                        verbose_name="Celery 任务 ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Pending"),
                            (1, "Running"),
                            (2, "Success"),
                            (3, "Failed"),
                            (4, "Cancelled"),
                        ],
                        db_index=True,
                        default=0,
                        verbose_name="构建状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="开始时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True,
                        help_text="由 save() 根据开始/结束时间自动计算。",
                        null=True,
                        verbose_name="构建持续时间",
                    ),
                ),
                (
                    "docker_image",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="例如 registry.example.com/app:1.0.0；无则留空。",
                        max_length=512,
                        verbose_name="构建镜像名称",
                    ),
                ),
                (
                    "artifact_download_url",
                    models.URLField(
                        blank=True,
                        help_text="包或制品的 HTTP(S) 下载链接；无则留空。",
                        max_length=1024,
                        null=True,
                        verbose_name="产物下载地址",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engine_build_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="触发用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "引擎构建记录",
                "verbose_name_plural": "引擎构建记录",
                "db_table": "engine_build_record",
                "ordering": ("-start_time", "-pk"),
            },
        ),
    ]
