# Generated by Django 4.2.20 on 2026-04-14 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteLogServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                ("name", models.CharField(max_length=128, verbose_name="显示名称")),
                ("host", models.CharField(max_length=255, verbose_name="主机地址")),
                (
                    "port",
                    models.PositiveIntegerField(default=22, verbose_name="SSH 端口"),
                ),
                (
                    "username",
                    models.CharField(max_length=128, verbose_name="SSH 用户名"),
                ),
                (
                    "password_enc",
                    models.TextField(blank=True, default="", verbose_name="密码密文"),
                ),
                (
                    "private_key_enc",
                    models.TextField(blank=True, default="", verbose_name="私钥密文"),
                ),
                (
                    "server_type",
                    models.CharField(
                        choices=[("linux", "Linux"), ("windows", "Windows")],
                        default="linux",
                        max_length=16,
                        verbose_name="系统类型",
                    ),
                ),
                (
                    "default_log_path",
                    models.CharField(
                        default="/var/log/syslog",
                        max_length=1024,
                        verbose_name="默认日志路径",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "updater",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "远程日志服务器",
                "db_table": "server_logs_remote_host",
                "ordering": ("-update_time",),
            },
        ),
    ]
