# Generated by Django 4.2.20 on 2026-04-14 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server_logs", "0002_remotelogserver_organization_serverlogauditevent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="serverlogauditevent",
            options={"ordering": ("-created_at",), "verbose_name": "服务器日志审计"},
        ),
    ]
