# Generated by Django 4.2.30 on 2026-04-14 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("server_logs", "0003_alter_serverlogauditevent_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serverlogauditevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("ws_connect", "实时日志连接"),
                    ("ws_disconnect", "实时日志断开"),
                    ("ws_stop", "停止 tail"),
                    ("analyze", "AI 诊断"),
                    ("auto_ticket", "AI 工单草稿"),
                    ("search", "历史检索"),
                    ("host_create", "新增主机"),
                    ("host_update", "更新主机"),
                    ("host_delete", "删除主机"),
                ],
                db_index=True,
                max_length=40,
                verbose_name="动作",
            ),
        ),
        migrations.CreateModel(
            name="LogAutoTicketJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anchor_text", models.TextField(verbose_name="锚点文本")),
                (
                    "anchor_ts",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="锚点时间戳(ms)"
                    ),
                ),
                (
                    "window_seconds",
                    models.PositiveIntegerField(
                        default=300, verbose_name="上下文窗口(秒)"
                    ),
                ),
                (
                    "es_limit",
                    models.PositiveIntegerField(
                        default=200, verbose_name="ES 最大行数"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "排队中"),
                            ("processing", "处理中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Celery 任务 ID",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "draft",
                    models.JSONField(blank=True, null=True, verbose_name="草稿 JSON"),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="诊断元信息"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "remote_log_server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_ticket_jobs",
                        to="server_logs.remotelogserver",
                        verbose_name="关联主机",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_auto_ticket_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发起人",
                    ),
                ),
            ],
            options={
                "verbose_name": "日志 AI 工单草稿任务",
                "db_table": "server_logs_auto_ticket_job",
                "ordering": ("-created_at",),
            },
        ),
    ]
