# Generated by Django 4.2.30 on 2026-04-14 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testcase", "0024_apitestcase_api_source_curl"),
        ("defect", "0004_alter_testdefect_is_deleted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0006_releaseplan_test_cases"),
        ("server_logs", "0004_log_auto_ticket_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="logautoticketjob",
            name="create_defect_requested",
            field=models.BooleanField(default=False, verbose_name="是否请求创建缺陷"),
        ),
        migrations.AddField(
            model_name="logautoticketjob",
            name="created_defect",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_log_auto_ticket_jobs",
                to="defect.testdefect",
                verbose_name="已创建的缺陷",
            ),
        ),
        migrations.AddField(
            model_name="logautoticketjob",
            name="defect_handler",
            field=models.ForeignKey(
                blank=True,
                help_text="留空则使用任务发起人作为处理人。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="log_auto_ticket_jobs_as_handler",
                to=settings.AUTH_USER_MODEL,
                verbose_name="缺陷处理人",
            ),
        ),
        migrations.AddField(
            model_name="logautoticketjob",
            name="defect_module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="log_auto_ticket_jobs",
                to="testcase.testmodule",
                verbose_name="缺陷所属模块",
            ),
        ),
        migrations.AddField(
            model_name="logautoticketjob",
            name="defect_release_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="log_auto_ticket_jobs",
                to="project.releaseplan",
                verbose_name="缺陷关联版本",
            ),
        ),
    ]
