# Generated by Django 4.2.20 on 2026-04-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server_logs", "0006_update_default_log_path_to_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remotelogserver",
            name="default_log_path",
            field=models.CharField(
                default="/var/log/messages",
                max_length=1024,
                verbose_name="默认日志路径",
            ),
        ),
    ]
